### ISSUE TITLE
Support click 8

### ISSUE THREAD

**Issue by cancan101** [anvilco/python-anvil#19]
Currently the version dependency on click is pinned to `^7.0`

**Comment by wstewarttennes** [comment]
`#8 77.43
#8 77.43 The conflict is caused by:
#8 77.43     celery 5.2.3 depends on click<9.0 and >=8.0.3
#8 77.43     celery[sqs] 5.2.3 depends on click<9.0 and >=8.0.3
#8 77.43     python-anvil 1.3.0 depends on click<8.0 and >=7.0`

+1 on this, I can't use this package until click dependency is fixed

**Comment by aalmazan** [comment]
`click` will be updated on the next release today. Didn't expect major package conflicts like `celery`, so the CLI portion of this package will probably be split out into an optional dependency for those who want it. 

Thanks again for the reports.
